<a href="https://colab.research.google.com/github/KshitijPriyank/Python/blob/main/21_9_2020_KSHITIJ_PROJECT_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***ACTIVITY 1.1:-***

In [ ]:
#Activity 1.1: Pandas Series containing Random Integers
#Create a Pandas series containing 40 random integers between 130 and 145. Print this series.
import pandas as pd
import random
var = pd.Series([random.randint(130, 146) for i in range(40)])
print("panda series:",var)

panda series: 0     133
1     134
2     138
3     141
4     141
5     144
6     132
7     139
8     143
9     136
10    135
11    141
12    131
13    146
14    131
15    133
16    140
17    145
18    130
19    136
20    141
21    139
22    143
23    141
24    144
25    143
26    139
27    138
28    138
29    141
30    136
31    137
32    136
33    139
34    133
35    143
36    131
37    134
38    134
39    139
dtype: int64


***ACTIVITY 1.2:-***

In [ ]:
#Activity 1.2: Calculate Mean and Median
#Calculate the mean value and median value of the above Pandas series.
print("mean is ",var.mean())
print("median is ",var.median())

mean is  137.95
median is  138.5


***ACTIVITY 1.3:-***

In [ ]:
#Activity 1.3: Find Minimum and Maximum
#Find the minimum and maximum value in the above Pandas series
print("min is ",var.min())
print("max is ",var.max())

min is  130
max is  146


***ACTIVITY 1.4:-***

In [ ]:
#Activity 1.4: Arrange in Descending Order
#Arrange the values in descending order and print the last five rows of the series.
print("the descending values of list",var.sort_values(ascending=False))

the descending values of list 13    146
17    145
5     144
24    144
35    143
8     143
22    143
25    143
11    141
23    141
3     141
4     141
20    141
29    141
16    140
21    139
39    139
26    139
7     139
33    139
28    138
2     138
27    138
31    137
9     136
19    136
30    136
32    136
10    135
38    134
37    134
1     134
15    133
34    133
0     133
6     132
14    131
12    131
36    131
18    130
dtype: int64


***ACTIVITY 2:-***

In [ ]:
#Activity 2: Find whether Two Lines are Parallel
def parallel_lines(line1,line2):
  slope1=line1[0]/line1[1]
  slope2=line2[0]/line2[1]
  if slope1==slope2:
    return True
  else:
    return False

line1=[2,3,4]
line2=[4,6,8]
print('are lines parallel?')
parallel_lines(line1,line2)

are lines parallel


True

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

  1.  Python List II
  3.  Pandas Series

---

#### Getting Started:

1. Click on this link to open the Colab file for this project.

     https://colab.research.google.com/drive/1RkKhzVNCjkDoO9JEXGHMr0ucDK4kQN5R?usp=sharing
     
2. Create a duplicate copy of the Colab file as described below.

  - Click on the **File menu**. A new drop-down list will appear.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/0_file_menu.png' width=500>

  - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-0/1_create_colab_duplicate_copy.png' width=500>

3. After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project13** format.

4. Now, write your code in the prescribed code cells.


### Activities

#### Activity 1.1: Pandas Series containing Random Integers

Create a Pandas series containing 40 random integers between 130 and 145. Print this series.

In [ ]:
# Create Pandas series



---

#### Activity 1.2: Calculate Mean and Median

Calculate the mean value and median value of the above Pandas series.

In [ ]:
# Calculate the mean and median value


---

#### Activity 1.3: Find Minimum and Maximum

Find the minimum and maximum value in the above Pandas series.

In [ ]:
# Find minimum and maximum value in the above Pandas series


---

#### Activity 1.4: Arrange in Descending Order

Arrange the values in descending order and print the last five rows of the series.

In [ ]:
# Arrange the values in descending order and print the last five rows


---

#### Activity 2: Find whether Two Lines are Parallel

Given two lines, determine whether they are parallel or not.
Lines are represented using a list [a, b, c] which corresponds to the straight line $ax+by=c$.



**Hints:**
- Two lines are parallel if their slopes are equal.

- A line in the form of $ax+by=c$ has slope $\frac {-a}{b}$.
- Ignore the minus (-) sign. Just calculate $\frac {a}{b}$ for both lines and find out whether they are equal or not.


**Example:**
```
line1 = [2,3,4]
line2 = [4,6,8]

Are lines parallel?
True
```


In [ ]:
# Two lines are parallel or not


---

### How To Submit The Project

Follow the steps described below to submit the project.
1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.
  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>
2. In the dialog box, click on the **Copy link** button. Make sure that '**Anyone on the Internet with this link can view**' option is selected and then click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>
3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project13**) of the notebook will get copied
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>
4. Go to your dashboard and click on the **My Projects** option.
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>
5. Click on the **View Project** button for the project you want to submit.
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>
6. Click on the **Submit Project Here** button.
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>
7. Past the link to the project named as **YYYY-MM-DD_StudentName_Project13** in the URL box and then click on the **Submit** button.
   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>


---